"""create quality evaluations table

Revision ID: 160ca8129b1f
Revises: c5fd64a31ba7
Create Date: 2026-09-12 09:19:36.953643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160ca8129b1f'
down_revision: Union[str, Sequence[str], None] = 'c5fd64a31ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('defect_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_items', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quality_status', sa.Enum('EXCELLENT', 'GOOD', 'ACCEPTABLE', 'POOR', 'CRITICAL', name='qualitystatus', native_enum=False, length=32), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('defect_count >= 0', name='ck_quality_evaluations_defect_count_non_negative'),
    sa.CheckConstraint('quality_score >= 0 AND quality_score <= 100', name='ck_quality_evaluations_score_range'),
    sa.CheckConstraint('total_items = 0 OR total_items >= defect_count', name='ck_quality_evaluations_defects_within_items'),
    sa.CheckConstraint('total_items >= 0', name='ck_quality_evaluations_total_items_non_negative'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_evaluations_contract_id'), 'quality_evaluations', ['contract_id'], unique=False)
    op.create_index(op.f('ix_quality_evaluations_created_by'), 'quality_evaluations', ['created_by'], unique=False)
    op.create_index(op.f('ix_quality_evaluations_purchase_order_id'), 'quality_evaluations', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_quality_evaluations_vendor_id'), 'quality_evaluations', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_evaluations_vendor_id'), table_name='quality_evaluations')
    op.drop_index(op.f('ix_quality_evaluations_purchase_order_id'), table_name='quality_evaluations')
    op.drop_index(op.f('ix_quality_evaluations_created_by'), table_name='quality_evaluations')
    op.drop_index(op.f('ix_quality_evaluations_contract_id'), table_name='quality_evaluations')
    op.drop_table('quality_evaluations')
    # ### end Alembic commands ###
