"""create contracts table

Revision ID: 2094b0b9e149
Revises: a90fb159e9aa
Create Date: 2026-09-11 08:40:15.502840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2094b0b9e149'
down_revision: Union[str, Sequence[str], None] = 'a90fb159e9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ON_HOLD', 'CANCELLED', 'EXPIRED', name='contractstatus', native_enum=False, length=32), server_default='DRAFT', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('contract_value >= 0', name='ck_contracts_contract_value_non_negative'),
    sa.CheckConstraint('end_date >= start_date', name='ck_contracts_end_date_after_start_date'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number')
    )
    op.create_index(op.f('ix_contracts_vendor_id'), 'contracts', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_vendor_id'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
