"""create purchase_orders table

Revision ID: c5fd64a31ba7
Revises: 2094b0b9e149
Create Date: 2026-09-11 21:55:42.484183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5fd64a31ba7'
down_revision: Union[str, Sequence[str], None] = '2094b0b9e149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=False),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'IN_PROGRESS', 'DELIVERED', 'PARTIALLY_DELIVERED', 'CANCELLED', 'CLOSED', name='purchaseorderstatus', native_enum=False, length=32), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_delivery_date IS NULL OR actual_delivery_date >= order_date', name='ck_purchase_orders_actual_delivery_after_order'),
    sa.CheckConstraint('expected_delivery_date >= order_date', name='ck_purchase_orders_expected_delivery_after_order'),
    sa.CheckConstraint('order_value >= 0', name='ck_purchase_orders_order_value_non_negative'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_purchase_orders_contract_id'), 'purchase_orders', ['contract_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_contract_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
